### ISSUE TITLE
Pilvo.py - Request.post for sms does not handle 401 responses

### ISSUE THREAD

**Issue by supritha** [plivo/plivo-python#13]
>> p.send_message(message_params)
Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    p.send_message(message_params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/plivo.py", line 496, in send_message
    return self._request('POST', '/Message/', data=params)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/plivo.py", line 78, in _request
    response = json.loads(content)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

**Comment by ankitpopli1891** [comment]
Fixed in https://github.com/plivo/plivo-python/pull/15, was facing the same issue.
