### ISSUE TITLE
plivoxml bug after moving from Python2 to Python3

### ISSUE THREAD

**Issue by yadomkar** [plivo/plivo-python#231]
The PlivoXMLElement.py module is attempting to decode a `__proxy__` object in Python 3, which is not allowed.

The `__proxy__` object is used by Django to provide translations and lazy evaluation of strings. In Python 3, strings are Unicode by default, so you shouldn't need to call `decode()` on them.

python2: (works)
`<class 'django.utils.functional.__proxy__'>`

python3: (breaks)
`<class 'django.utils.functional.lazy.<locals>.__proxy__'>`

Error log:
```Traceback (most recent call last):
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/plivo/xml/PlivoXMLElement.py", line 39, in _to_element
    e.text = self.content.decode()
AttributeError: '__proxy__' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/share/newfies/plivo_cloud/views.py", line 727, in app_answer_handler
    return HttpResponse(xml_response.to_string(), content_type='application/xml')
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/plivo/xml/PlivoXMLElement.py", line 26, in to_string
    s = self.continue_speak(etree.tostring(self._to_element(), pretty_print=pretty, encoding='unicode'))
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/plivo/xml/PlivoXMLElement.py", line 43, in _to_element
    child._to_element(parent=e)
  File "/usr/share/virtualenvs/max/lib/python3.5/site-packages/plivo/xml/PlivoXMLElement.py", line 41, in _to_element
    e.text = self.content
  File "src/lxml/etree.pyx", line 1042, in lxml.etree._Element.text.__set__
  File "src/lxml/apihelpers.pxi", line 748, in lxml.etree._setNodeText
  File "src/lxml/apihelpers.pxi", line 736, in lxml.etree._createTextNode
  File "src/lxml/apihelpers.pxi", line 1539, in lxml.etree._utf8
TypeError: Argument must be bytes or unicode, got '__proxy__'

**Comment by yadomkar** [comment]
@mike-plivo Any update on this?

**Comment by likithplivo** [comment]
@yadomkar Can you share the sample code for the XML you are trying to generate? Also, it would be helpful if you could share the exact Python version used.

**Comment by yadomkar** [comment]
We are using `Python 3.5.2`

Adding a str over self.content will resolve the issue.
`e.text = str(self.content)`

**Comment by apoorv-plivo** [comment]
@yadomkar This issue has been fixed in the latest version v4.33.1
